sonar.organization=alexismetton
sonar.projectKey=AlexisMetton_kubesecurebox_portfolio_alexis_metton

sonar.sources=.
sonar.exclusions=.git/**,.github/**,**/node_modules/**,.next/**,out/**,.scannerwork/**,*.config.js,*.config.mjs,*.config.ts
